const path = require('path');
const dotenv = require('dotenv');
const mongoose = require('mongoose');

dotenv.config({ path: path.join(__dirname, '..', '.env') });

const Subject = require('../models/Subject');
const Course = require('../models/Course');
const FinalExamQuestionPaper = require('../models/FinalExamQuestionPaper');

const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI;

const args = new Set(process.argv.slice(2));
const dryRun = args.has('--dry-run');
const overwriteEmptyOnly = !args.has('--overwrite');

const isExcludedSubject = (subject) => {
    const combined = [
        subject?.name,
        subject?.printedName,
        subject?.topicName
    ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();

    return /\b(discipline|project)\b/.test(combined);
};

const buildPlaceholderMcqs = (subjectName) => {
    const label = String(subjectName || 'Subject').trim();
    return Array.from({ length: 50 }, (_, index) => ({
        question: `${label} MCQ ${index + 1}`,
        options: [
            `Option A ${index + 1}`,
            `Option B ${index + 1}`,
            `Option C ${index + 1}`,
            `Option D ${index + 1}`
        ],
        correctAnswer: `Option A ${index + 1}`,
        marks: 1
    }));
};

const buildPlaceholderQuestionAnswers = (subjectName) => {
    const label = String(subjectName || 'Subject').trim();
    return Array.from({ length: 5 }, (_, index) => ({
        question: `${label} Question Answer ${index + 1}`,
        answer: `Write the answer for ${label} Question ${index + 1}`,
        marks: 10
    }));
};

const normalizePaperSubject = (subjectDoc) => ({
    subject: subjectDoc._id,
    duration: '',
    mcqs: buildPlaceholderMcqs(subjectDoc.printedName || subjectDoc.name),
    questionAnswers: buildPlaceholderQuestionAnswers(subjectDoc.printedName || subjectDoc.name)
});

const hasMeaningfulContent = (row) =>
    (row?.mcqs || []).length > 0 || (row?.questionAnswers || []).length > 0;

const seedMissingAnswers = (subjectRow, subjectName) => {
    const label = String(subjectName || 'Subject').trim();

    subjectRow.mcqs = (subjectRow.mcqs || []).map((mcq, index) => ({
        ...mcq,
        correctAnswer: String(mcq.correctAnswer || '').trim() || `Option A ${index + 1}`
    }));

    subjectRow.questionAnswers = (subjectRow.questionAnswers || []).map((qa, index) => ({
        ...qa,
        answer: String(qa.answer || '').trim() || `Write the answer for ${label} Question ${index + 1}`
    }));
};

const run = async () => {
    if (!mongoUri) {
        throw new Error('MONGO_URI or MONGODB_URI is required');
    }

    await mongoose.connect(mongoUri, { serverSelectionTimeoutMS: 10000 });

    const courses = await Course.find({ isDeleted: false, isActive: true })
        .populate({
            path: 'subjects.subject',
            select: 'name printedName topicName isDeleted isActive'
        })
        .lean();

    let createdPapers = 0;
    let updatedPapers = 0;
    let addedSubjects = 0;
    let skippedSubjects = 0;

    for (const course of courses) {
        const eligibleSubjects = [...(course.subjects || [])]
            .map((item) => item.subject)
            .filter(Boolean)
            .filter((subject) => !subject.isDeleted && subject.isActive !== false && !isExcludedSubject(subject))
            .filter((subject, index, list) =>
                list.findIndex((item) => String(item._id) === String(subject._id)) === index
            );

        if (!eligibleSubjects.length) {
            continue;
        }

        const existingPaper = await FinalExamQuestionPaper.findOne({
            isDeleted: false,
            course: course._id
        });

        const existingSubjectIds = new Set(
            (existingPaper?.subjects || []).map((row) => String(row.subject?._id || row.subject))
        );

        const missingSubjects = eligibleSubjects
            .filter((subject) => !existingSubjectIds.has(String(subject._id)))
            .map(normalizePaperSubject);

        const emptyExistingRows = (existingPaper?.subjects || [])
            .filter((row) => !hasMeaningfulContent(row));

        if (!existingPaper) {
            if (dryRun) {
                createdPapers += 1;
                addedSubjects += eligibleSubjects.length;
                continue;
            }

            await FinalExamQuestionPaper.create({
                title: `${course.name} Question Paper`,
                examName: 'Final Exam',
                course: course._id,
                subjects: eligibleSubjects.map(normalizePaperSubject),
                remarks: 'Auto-generated by seedFinalExamQuestionPapers script',
                isActive: true
            });

            createdPapers += 1;
            addedSubjects += eligibleSubjects.length;
            continue;
        }

        const shouldSeedEmptyRows = overwriteEmptyOnly && emptyExistingRows.length > 0;
        const nextSubjects = [...(existingPaper.subjects || [])];

        if (missingSubjects.length > 0) {
            nextSubjects.push(...missingSubjects);
            addedSubjects += missingSubjects.length;
        }

        if (shouldSeedEmptyRows) {
            for (const row of nextSubjects) {
                if (hasMeaningfulContent(row)) continue;
                const subjectDoc = eligibleSubjects.find((subject) =>
                    String(subject._id) === String(row.subject?._id || row.subject)
                );
                if (!subjectDoc) continue;
                row.duration = row.duration || '';
                row.mcqs = buildPlaceholderMcqs(subjectDoc.printedName || subjectDoc.name);
                row.questionAnswers = buildPlaceholderQuestionAnswers(subjectDoc.printedName || subjectDoc.name);
                skippedSubjects += 0;
            }
        }

        for (const row of nextSubjects) {
            const subjectDoc = eligibleSubjects.find((subject) =>
                String(subject._id) === String(row.subject?._id || row.subject)
            );
            if (!subjectDoc) continue;
            seedMissingAnswers(row, subjectDoc.printedName || subjectDoc.name);
        }

        const needsUpdate =
            missingSubjects.length > 0 ||
            (shouldSeedEmptyRows && emptyExistingRows.length > 0);

        if (!needsUpdate) {
            skippedSubjects += eligibleSubjects.length;
            continue;
        }

        if (dryRun) {
            updatedPapers += 1;
            continue;
        }

        existingPaper.subjects = nextSubjects;
        if (!existingPaper.title) {
            existingPaper.title = `${course.name} Question Paper`;
        }
        if (!existingPaper.examName) {
            existingPaper.examName = 'Final Exam';
        }
        existingPaper.isActive = existingPaper.isActive !== false;
        await existingPaper.save();
        updatedPapers += 1;
    }

    console.log(JSON.stringify({
        dryRun,
        createdPapers,
        updatedPapers,
        addedSubjects,
        skippedSubjects
    }, null, 2));
};

run()
    .then(async () => {
        await mongoose.connection.close();
        process.exit(0);
    })
    .catch(async (error) => {
        console.error(error);
        try {
            await mongoose.connection.close();
        } catch (closeError) {
            // ignore
        }
        process.exit(1);
    });
